name: indidus_password_manager
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.3+9

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.14.0
  collection: ^1.18.0
  dropdown_button2: ^2.3.9
  easy_debounce: ^2.0.3
  firebase_analytics: ^10.8.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_performance: 0.9.3+8
  firebase_performance_platform_interface: 0.1.4+16
  firebase_performance_web: 0.1.4+16
  flutter_animate: ^4.4.1
  flutter_cache_manager: 3.3.1
  flutter_native_splash: ^2.3.9
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  from_css_color: ^2.0.0
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  hive: 2.2.3
  intl: 0.18.1
  json_path: ^0.7.0
  lottie: ^3.0.0
  mask_text_input_formatter: ^2.8.0
  page_transition: ^2.1.0
  path_provider: ^2.1.2
  path_provider_android: ^2.2.2
  path_provider_foundation: ^2.3.2
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.1
  rxdart: 0.27.7
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: ^2.3.5
  shared_preferences_platform_interface: ^2.3.2
  shared_preferences_web: ^2.2.2
  sign_in_with_apple: ^5.0.0
  sqflite: ^2.3.1
  stream_transform: ^2.1.0
  supabase: ^2.0.6
  supabase_flutter: ^2.3.1
  timeago: ^3.6.0
  universal_io: 2.2.2
  url_launcher: ^6.2.4
  url_launcher_android: ^6.2.2
  url_launcher_ios: ^6.2.4
  url_launcher_platform_interface: ^2.3.1
  webview_flutter: ^4.4.4
  webview_flutter_android: ^3.14.0
  webview_flutter_platform_interface: ^2.10.0
  webview_flutter_wkwebview: ^3.11.0

  flutter_rust_bridge: 2.0.0-dev.22
  rust_builder:
    path: rust_builder


dependency_overrides:
  rxdart: ^0.27.7

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  image: ^4.0.17
  lints: ^3.0.0
  flutter_web_plugins:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
  fonts:
    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
