// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.28.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import '../frb_generated.dart';

part 'financial_cards.freezed.dart';
part 'financial_cards.g.dart';

@freezed
class FinancialCard with _$FinancialCard {
  const factory FinancialCard({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    DateTime? updatedAt,
    String? updatedBy,
    required String cardHolderName,
    required String cardNumber,
    String? cardProviderName,
    String? cardType,
    String? cvv,
    String? expiryDate,
    String? issueDate,
    required String name,
    String? note,
    String? pin,
  }) = _FinancialCard;

  factory FinancialCard.fromJson(Map<String, dynamic> json) =>
      _$FinancialCardFromJson(json);
}
