// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.28.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import '../frb_generated.dart';

part 'identity_cards.freezed.dart';
part 'identity_cards.g.dart';

@freezed
class IdentityCard with _$IdentityCard {
  const factory IdentityCard({
    String? id,
    DateTime? createdAt,
    String? createdBy,
    DateTime? updatedAt,
    String? updatedBy,
    required String name,
    String? note,
    String? country,
    String? expiryDate,
    required String identityCardNumber,
    String? identityCardType,
    String? issueDate,
    required String nameOnCard,
    String? state,
  }) = _IdentityCard;

  factory IdentityCard.fromJson(Map<String, dynamic> json) =>
      _$IdentityCardFromJson(json);
}
