// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADw-lBeQsmSB6K6cVnWOdyhL2O-gmCybg',
    appId: '1:867001464038:web:8f14ea87eecac31909b727',
    messagingSenderId: '867001464038',
    projectId: 'indidus-password-manager',
    authDomain: 'indidus-password-manager.firebaseapp.com',
    storageBucket: 'indidus-password-manager.appspot.com',
    measurementId: 'G-FYTR6MS5C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbWIXm84GRI0lDUA6b3EiK3UaGVDC2N2c',
    appId: '1:867001464038:android:e407a170f8f0aebb09b727',
    messagingSenderId: '867001464038',
    projectId: 'indidus-password-manager',
    storageBucket: 'indidus-password-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6sCWiSETM8oYlfVAGR42BRHUE1XUeV9I',
    appId: '1:867001464038:ios:5a2f41bf32d9bfe309b727',
    messagingSenderId: '867001464038',
    projectId: 'indidus-password-manager',
    storageBucket: 'indidus-password-manager.appspot.com',
    androidClientId: '867001464038-337c7ada4rbh1vuitac7hddl2tjr99aq.apps.googleusercontent.com',
    iosClientId: '867001464038-iucvta5m7t0ppra5i2m9pvlheht26rct.apps.googleusercontent.com',
    iosBundleId: 'com.indidus.password',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6sCWiSETM8oYlfVAGR42BRHUE1XUeV9I',
    appId: '1:867001464038:ios:0ca4fdabe931bec309b727',
    messagingSenderId: '867001464038',
    projectId: 'indidus-password-manager',
    storageBucket: 'indidus-password-manager.appspot.com',
    androidClientId: '867001464038-337c7ada4rbh1vuitac7hddl2tjr99aq.apps.googleusercontent.com',
    iosClientId: '867001464038-ojpfao2b53bsbne1uf6gnb882hv1kj5h.apps.googleusercontent.com',
    iosBundleId: 'com.indidus.password.RunnerTests',
  );
}
