name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: aws-t2-micro

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.1'
          channel: 'stable'
      - run: flutter --version

      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y 
          echo "$HOME/.cargo/env" >> $GITHUB_PATH
      - name: Validate rust installation
        run: cargo --version
      - name: Install just
        run: cargo install just
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          ref: main
