name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: aws-t2-micro

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.1'
          channel: 'stable'
      - run: flutter --version
      
      - run: curl https://sh.rustup.rs -sSf | sh
