name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Setup just
        uses: extractions/setup-just@v2

      - name: Build app bundle
        run: |
          git config --global url."https://ashim-kr-saha:${{secrets.GH_PAT}}@github.com".insteadOf "https://github.com"
          just abb
 
