name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: aws-t2-micro

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.1'
          channel: 'stable'
      - run: flutter --version
        
      - name: Insall essential
        run: sudo apt install build-essential
      
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install just
        run: cargo install just
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          ref: main
