name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: aws-t2-micro

    steps:
      # - uses: actions/checkout@v4
      # - uses: subosito/flutter-action@v2
      #   with:
      #     flutter-version: '3.19.1'
      #     channel: 'stable'
      # - run: flutter --version
        
      # - name: Insall essential
      #   run: |
      #     sudo apt-get update
      #     sudo apt install build-essential -y
      #     sudo apt install unzip
      
      # - uses: actions/checkout@v3
      # - uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      # - name: Install just
      #   run: cargo install just
  
      # - name: Set up JDK 17
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '17'
      #     distribution: 'temurin'
      # - name: Setup Android SDK
      #   uses: android-actions/setup-android@v3
      
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          ref: main
      - name: Build appbundle
        run: |
          git config --global url."https://ashim-kr-saha:${{secrets.GH_PAT}}@github.com".insteadOf "https://github.com"
          just abb
