// ignore_for_file: constant_identifier_names

const String CREATE_NOTE_INITIATE = "CREATE_NOTE_INITIATE";
const String CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";
const String CREATE_NOTE_FAILURE = "CREATE_NOTE_FAILURE";
const String UPDATE_NOTE_INITIATE = "UPDATE_NOTE_INITIATE";
const String UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";
const String UPDATE_NOTE_FAILURE = "UPDATE_NOTE_FAILURE";
const String DELETE_NOTE_INITIATE = "DELETE_NOTE_INITIATE";
const String DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
const String DELETE_NOTE_FAILURE = "DELETE_NOTE_FAILURE";
const String GET_NOTES_INITIATE = "GET_NOTES_INITIATE";
const String GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";
const String GET_NOTES_FAILURE = "GET_NOTES_FAILURE";
const String GET_NOTE_INITIATE = "GET_NOTE_INITIATE";
const String GET_NOTE_SUCCESS = "GET_NOTE_SUCCESS";
const String GET_NOTE_FAILURE = "GET_NOTE_FAILURE";

// LOGIN
const String CREATE_LOGIN_INITIATE = "CREATE_LOGIN_INITIATE";
const String CREATE_LOGIN_SUCCESS = "CREATE_LOGIN_SUCCESS";
const String CREATE_LOGIN_FAILURE = "CREATE_LOGIN_FAILURE";
const String UPDATE_LOGIN_INITIATE = "UPDATE_LOGIN_INITIATE";
const String UPDATE_LOGIN_SUCCESS = "UPDATE_LOGIN_SUCCESS";
const String UPDATE_LOGIN_FAILURE = "UPDATE_LOGIN_FAILURE";
const String DELETE_LOGIN_INITIATE = "DELETE_LOGIN_INITIATE";
const String DELETE_LOGIN_SUCCESS = "DELETE_LOGIN_SUCCESS";
const String DELETE_LOGIN_FAILURE = "DELETE_LOGIN_FAILURE";
const String GET_LOGINS_INITIATE = "GET_LOGINS_INITIATE";
const String GET_LOGINS_SUCCESS = "GET_LOGINS_SUCCESS";
const String GET_LOGINS_FAILURE = "GET_LOGINS_FAILURE";
const String GET_LOGIN_INITIATE = "GET_LOGIN_INITIATE";
const String GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";
const String GET_LOGIN_FAILURE = "GET_LOGIN_FAILURE";

// FINANCIAL
const String CREATE_FINANCIAL_INITIATE = "CREATE_FINANCIAL_INITIATE";
const String CREATE_FINANCIAL_SUCCESS = "CREATE_FINANCIAL_SUCCESS";
const String CREATE_FINANCIAL_FAILURE = "CREATE_FINANCIAL_FAILURE";
const String UPDATE_FINANCIAL_INITIATE = "UPDATE_FINANCIAL_INITIATE";
const String UPDATE_FINANCIAL_SUCCESS = "UPDATE_FINANCIAL_SUCCESS";
const String UPDATE_FINANCIAL_FAILURE = "UPDATE_FINANCIAL_FAILURE";
const String DELETE_FINANCIAL_INITIATE = "DELETE_FINANCIAL_INITIATE";
const String DELETE_FINANCIAL_SUCCESS = "DELETE_FINANCIAL_SUCCESS";
const String DELETE_FINANCIAL_FAILURE = "DELETE_FINANCIAL_FAILURE";
const String GET_FINANCIALS_INITIATE = "GET_FINANCIALS_INITIATE";
const String GET_FINANCIALS_SUCCESS = "GET_FINANCIALS_SUCCESS";
const String GET_FINANCIALS_FAILURE = "GET_FINANCIALS_FAILURE";
const String GET_FINANCIAL_INITIATE = "GET_FINANCIAL_INITIATE";
const String GET_FINANCIAL_SUCCESS = "GET_FINANCIAL_SUCCESS";
const String GET_FINANCIAL_FAILURE = "GET_FINANCIAL_FAILURE";

// IDENTITY
const String CREATE_IDENTITY_INITIATE = "CREATE_IDENTITY_INITIATE";
const String CREATE_IDENTITY_SUCCESS = "CREATE_IDENTITY_SUCCESS";
const String CREATE_IDENTITY_FAILURE = "CREATE_IDENTITY_FAILURE";
const String UPDATE_IDENTITY_INITIATE = "UPDATE_IDENTITY_INITIATE";
const String UPDATE_IDENTITY_SUCCESS = "UPDATE_IDENTITY_SUCCESS";
const String UPDATE_IDENTITY_FAILURE = "UPDATE_IDENTITY_FAILURE";
const String DELETE_IDENTITY_INITIATE = "DELETE_IDENTITY_INITIATE";
const String DELETE_IDENTITY_SUCCESS = "DELETE_IDENTITY_SUCCESS";
const String DELETE_IDENTITY_FAILURE = "DELETE_IDENTITY_FAILURE";
const String GET_IDENTITIES_INITIATE = "GET_IDENTITIES_INITIATE";
const String GET_IDENTITIES_SUCCESS = "GET_IDENTITIES_SUCCESS";
const String GET_IDENTITIES_FAILURE = "GET_IDENTITIES_FAILURE";
const String GET_IDENTITY_INITIATE = "GET_IDENTITY_INITIATE";
const String GET_IDENTITY_SUCCESS = "GET_IDENTITY_SUCCESS";
const String GET_IDENTITY_FAILURE = "GET_IDENTITY_FAILURE";
